#!/usr/bin/env bash
set -e
set -o pipefail

additional_flags=""
additional_packages=""

# Load environment variables from .env file
if [ -f .env ]; then
    while read line || [ -n "$line" ]
    do
        if [[ ! "$line" =~ ^#.*$ && -n "$line" ]]; then
            if [[ $line == ADDITIONAL_PACKAGES=* ]]; then
                packages="${line#ADDITIONAL_PACKAGES=}"
                additional_packages+="$packages"
            else
                additional_flags+="--env '$line' "
            fi
        fi
    done < "./.env"
    # Remove trailing space
    additional_flags="${additional_flags%"${additional_flags##*[![:space:]]}"}"
    echo "Using additional flags: $additional_flags"
    # Replace placeholder in distrobox.ini.in and create distrobox.ini
    sed -E "s|^additional_flags=\"([^\"]*)\"$|additional_flags=\"\1 $additional_flags\"|" distrobox.ini.in > distrobox.ini
    
    sed -E "s|^###ADDITIONAL_PACKAGES###$|additional_packages=\"$additional_packages\"|" distrobox.ini > distrobox.ini.tmp && mv distrobox.ini.tmp distrobox.ini
    # Create the distrobox
    distrobox assemble create --replace
    # Start the distrobox
    distrobox enter cv
else
    echo ".env file not found!"
    exit 1
fi
