name: Nightly build
on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    #if: github.repository == 'CometVisu/CometVisu'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependecies
        run: pip install PyGithub sh
      - name: "Create tag on change"
        run: ./utils/ci/tagger --start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NIGHLTY_ONLY: 1
          COMMIT_AUTHOR_NAME: CometVisu-CI
          COMMIT_AUTHOR_EMAIL: generator@cometvisu.org
